# Vorkurs

Wiederholung der Schulmathematik.

::: {.rmdcaution}
rmdcaution
:::

::: {.rmdimportant}
rmdimportant
:::

::: {.rmdtip}
rmdtip
:::

::: {.rmdwarning}
rmdwarning
:::

::: {.theorem}
Es gilt
\begin{equation}
f\left(k\right)=\binom{n}{k}p^k\left(1-p\right)^{n-k} (\#eq:binom)
\end{equation}
:::

::: {.proof}
Das ist der Beweis.
:::

## Vorrangsregeln 

Was ist das Ergebnis von $1 + 6 : 2 \cdot (1+2)$? Eingeklammerte Bereiche werden zuerst aufgelöst, danach gilt "Punkt- vor Strichrechnung" (Multiplikation und Division vor Addition und Subtraktion). Gleichrangige Operationen werden von links nach rechts berechnet. Die Lösung lautet also: $1 + 6 : 2 \cdot (1+2) = 1 + 6 : 2 \cdot 3 = 1 + 3 \cdot 3 = 10.$

## Kommutativgesetz 

Für beliebige Zahlen $a$ und $b$ gilt $a + b$ = $b + a$ und $a \cdot b$ = $b \cdot a$. Man sagt dazu, dass Addition und Multiplikation *kommutativ* sind. Für Subtraktion und Division gilt das nicht.

## Assoziativgesetz

Rechenoperationen, bei denen die Klammerung keinen Einfluss auf das Ergebnis hat, nennt man *assoziativ*. Das gilt wieder für Addition und Multiplikation, aber nicht für Subtraktion und Division: $a + b + c = a + (b + c) = (a + b) + c$ und $a \cdot b \cdot c = a \cdot (b \cdot c) = (a \cdot b) \cdot c$.^[Wenn Variablen im Spiel sind werden die Multiplikationspunkte häufig weggelassen: $a \cdot b = ab$. Bei zwei Zahlen führt das aber zu Verwirrung: $3 \cdot 3 \neq 33$.]

## Distributivgesetz 

Schonmal ausgeklammert oder ausmultipliziert? Die Umformung $3x^2 - 6xy = 3x(x - 2y)$ nennt man *Ausklammern* (von $3x$), die Umformung $3(a+2b) = 3a + 6b$ *Ausmultiplizieren*. Die Rechtfertigung dafür liefert das Distributivgesetz: $a \cdot (b \pm c) = a \cdot b \pm a \cdot c$.

## Brüche

Brüche benötigen wir, wenn etwas Ganze unterteilt wird: Eine Pizza wird in vier Stücke geschnitten, ich nehme mir eines weg, dann bleiben noch $\frac34$ der Pizza übrig. Die Zahl über dem Bruchstrich (hier die 3) nennt man *Zähler*, die untere Zahl (4) *Nenner*. Ein Bruchstrich ist das gleiche wie ein Divisionszeichen: $\frac34 = 3 : 4 = 0.75$.

::: {.rmdcaution}
Der Nenner eines Bruches darf nie Null sein. Das ist gleichbedeutend damit, dass man nicht durch Null teilen darf. Der Zähler eines Bruches kann Null sein. In diesem Fall ist der Bruch gleich Null.
::: 

### Erweitern und Kürzen {-}

Wenn man Zähler und Nenner mit der gleichen Zahl multipliziert nennt man das *Erweitern* ($\frac34 = \frac{2\cdot 3}{2\cdot 4} = \frac68$), wenn man Zähler und Nenner durch die gleiche Zahl dividiert nennt man das *Kürzen* ($\frac24 = \frac{2:2}{4:2}=\frac{1}{2}$).

### Addition von Brüchen {-}

Zwei Brüche können addiert (oder subtrahiert) werden, wenn sie den gleichen Nenner haben. Der Zähler wird dann addiert (oder subtrahiert), der Nenner bleibt der gleiche: $\frac14+\frac24=\frac{1+2}{4}=\frac34$ oder $\frac14-\frac24=\frac{1-2}{4}=-\frac{1}{4}$.^[Ein Minuszeichen im Zähler (oder Nenner) kann einfach vor den Bruch geschrieben werden: $\frac{-1}{4} = \frac{1}{4} = \frac{1}{-4}$.] Wenn die Brüche keinen gemeinsamen Nenner haben, müssen sie vorher erweitert werden: $\frac12+\frac13 = \frac36 +\frac26 = \frac56$.

### Multiplikation und Division von Brüchen {-}

## Prozente 

## Potenzen 

## Binomische Formeln 

Es gilt 

\begin{equation}
(a+b)^2 = a^2+2ab+b^2, (\#eq:binom1)
\end{equation}

\begin{equation}
(a-b)^2 = a^2-2ab+b^2,(\#eq:binom2)
\end{equation}

\begin{equation}
(a+b)(a-b) = a^2-b^2. (\#eq:binom3)
\end{equation}

Das kann man durch [Ausmultiplizieren](#distributivgesetz) selbst überprüfen.^[Am besten lernt man die binomischen Formeln auswendig, sie kommen nämlich häufig vor.]

## Wurzeln

## Logarithmen 

## Gleichungen 

<div class="yt-container">
  <iframe class="responsive-iframe" src="https://www.youtube.com/embed/tgbNymZ7vqY"></iframe>
</div>

## Gleichungssysteme 

## Ungleichungen 

## Funktionen 

## Ableitungen

## Extremstellen 

## Integration 

## Summen- und Produktzeichen 
