--- 
title: "Mathe für WiWis"
author: "Lennart Oelschläger"
date: "`r format(Sys.Date(), '%d.%m.%Y')`"
description: |
  Inhalte der einführenden Mathe Vorlesungen für Wirtschaftswissenschaftler
site: bookdown::bookdown_site
documentclass: book
url: https://loelschaeger.de/mathe_fuer_wiwis
---

# Willkommen {-}

Von Ökonomen wird erwartet, dass sie gut rechnen und logisch denken können. Deshalb beschäftigen sich angehende Wirtschaftswissenschaftler ab Studienbeginn mit Mathematik. An den meisten Hochschulen wird Mathematik deutlich formaler gelehrt als an Schulen. Viele Studienanfänger sind der neuen Ausrichtung zunächst wenig zugeneigt. Lass uns gemeinsam anfängliche Hürden überwinden! &#129351;

::: {.rmdwarning}
Dieses eBook entsteht während des Wintersemesters 2022/23 und des Sommersemesters 2023 und wird laufend überarbeitet. [Benachrichtige mich](#dein-feedback) bitte bei Fehlern oder Ergänzungswünschen.
:::

## Inhalte {-}

Wir besprechen die klassischen Themen der Mathematik Vorlesung in den ersten Semestern des Wirtschaftsstudiums, von [Aussagenlogik](aussagenlogik.html) bis [Optimierung](optimierung.html). Verstreut wirst du auch ein paar Übungen und Videos finden.

## Über mich {-}

Ich bin Lennart, habe Wirtschaftsmathematik studiert und promoviere gerade in Statistik an der Uni Bielefeld. Mehr über mich steht auf [meiner Webseite](https://loelschlaeger.de/). &#x1F913;

## Dein Feedback {-}

Ich freue mich über jeden Verbesserungsvorschlag, der mir [per E-Mail](mailto:oelschlaeger.lennart@gmail.com) zugesendet wird. Mit einem [Github Account](https://www.github.com) kannst du jede Seite auch direkt selbst editieren.
