on:
  push:
    branches: [main, master]

jobs:
  render-book:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install bookdown
        run: Rscript -e 'install.packages("bookdown")'

      - name: Install downlit
        run: Rscript -e 'install.packages("downlit")'

      - name: Install xml2
        run: Rscript -e 'install.packages("xml2")'
      
      - name: Render book
        run: Rscript -e 'bookdown::render_book()'
      
      - name: Commit results
        run: |
          git config --local user.email "oelschlaeger.lennart@gmail.com"
          git config --local user.name "Lennart Oelschlaeger"
          git add .
          git commit -m 'Rendered book :books:' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
